# Generated by Django 6.0.4 on 2026-04-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_candidatura_ativo_empresa_ativo_vaga_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='email_contato',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
