# Generated by Django 6.0.4 on 2026-04-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_empresa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(default='', max_length=18),
            preserve_default=False,
        ),
    ]
